#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Sidecar PR check

on:
    pull_request:
      paths:
      - 'sidecars/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed files
      id: getfile
      run: |
<<<<<<< HEAD:.github/workflows/sidecar-pr-checks.yaml
          echo $(git diff --name-only ${{ github.base_ref }})
=======
          echo $(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
>>>>>>> 3a91e79... Add demo GitHub PR check and some sample sidecars:.github/workflows/icons-extensions-pr-check.yaml

